# uncomment for init database (first start)
#spring.datasource.initialization-mode: always
#spring.datasource.schema: classpath*:db/mariadb/initDB.sql
#spring.datasource.data: classpath*:db/mariadb/populateDB.sql
# MariaDB config start
#----------------------------------------------------------------
spring:
  datasource:
    url: jdbc:mariadb://${DB_HOSTNAME:localhost}:3306/petclinic?useUnicode=true
    username: pc
    password: pc
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database: MYSQL
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate.ddl-auto: none
    open-in-view: true
#----------------------------------------------------------------
# MariaDB config end
